### ISSUE TITLE
put on hackage?

### ISSUE THREAD

**Issue by winterland1989** [Soostone/cereal-io-streams#1]
Why not put on hackage, it's very useful.

**Comment by MichaelXavier** [comment]
Good question. @ozataman any objection? Looks like I already have a test suite for this and its passing.

**Comment by ozataman** [comment]
I haven't used it in ages but I guess we can put it up there and let people file issues if any. Ideally someone could take a look and confirm it should be working well. 

I did seriously use it for a little while though, which gives some assurance. 

No objections overall.

**Comment by MichaelXavier** [comment]
Done http://hackage.haskell.org/package/cereal-io-streams

**Comment by winterland1989** [comment]
FYI, i've rewritten this library [here](https://github.com/winterland1989/cereal-streams/blob/master/src/System/IO/Streams/Cereal.hs) because the change is too large:
- the orignal naming scheme is quiet difficult to get.
- the bench is not right, the data are not decoded in conduit version.
- decode function are bloated, and didn't filter out empty. so i completely rewrite it, (according to new benchmark it's also faster)
- replace `Put -> IO (InputStream ByteString)` to `Put -> IO (OutputStream ByteString)`.

**Comment by ozataman** [comment]
If you would like to contribute your changes back, I'd suggest you create a pull request so we can compare/contrast and merge in if all's well.

**Comment by winterland1989** [comment]
I'll give a try after fixing the CI build. meanwhile you can review my code ; )
